import { Poppins } from "next/font/google";
import "./globals.css";
import Navebar from "@/Component/Navebar/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ge',
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navebar />
        {children}
      </body>
    </html>
  );
}
