import { Cinzel, Cinzel_Decorative, Poppins } from "next/font/google";
import "./globals.css";
import Navebar from "@/Component/Navebar/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400', '500', '600', '700'],
  variable: '--font-poppins',
  display:'swap'
});
const cinzel= Cinzel_Decorative({
  variable:'--font-cinzel',
  subsets:['latin'],
  weight:['400','700','900']
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by create Portfolio",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${cinzel.variable} antialiased`}>
        <Navebar />
        {children}
      </body>
    </html>
  );
}
